
language: elixir
elixir: 1.0.4
otp_release:
  - 17.1
sudo: false
install:
  - cd $TRAVIS_BUILD_DIR/server
  - mix local.hex --force
  - mix deps.get --force
  - mix ecto.create
  - mix phoenix.server &
before_script:
  - cd $TRAVIS_BUILD_DIR
  - npm install
script:
  - npm test

